package com.ragentek.exercisespaper.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ragentek.exercisespaper.dao.models.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property AccountId = new Property(0, Long.class, "accountId", true, "_id");
        public final static Property Identity = new Property(1, int.class, "identity", false, "IDENTITY");
        public final static Property GradeId = new Property(2, int.class, "gradeId", false, "GRADE_ID");
        public final static Property ClassId = new Property(3, int.class, "classId", false, "CLASS_ID");
    }

    private DaoSession daoSession;


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: accountId
                "\"IDENTITY\" INTEGER NOT NULL ," + // 1: identity
                "\"GRADE_ID\" INTEGER NOT NULL ," + // 2: gradeId
                "\"CLASS_ID\" INTEGER NOT NULL );"); // 3: classId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindLong(1, accountId);
        }
        stmt.bindLong(2, entity.getIdentity());
        stmt.bindLong(3, entity.getGradeId());
        stmt.bindLong(4, entity.getClassId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long accountId = entity.getAccountId();
        if (accountId != null) {
            stmt.bindLong(1, accountId);
        }
        stmt.bindLong(2, entity.getIdentity());
        stmt.bindLong(3, entity.getGradeId());
        stmt.bindLong(4, entity.getClassId());
    }

    @Override
    protected final void attachEntity(User entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // accountId
            cursor.getInt(offset + 1), // identity
            cursor.getInt(offset + 2), // gradeId
            cursor.getInt(offset + 3) // classId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setAccountId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setIdentity(cursor.getInt(offset + 1));
        entity.setGradeId(cursor.getInt(offset + 2));
        entity.setClassId(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setAccountId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getAccountId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getAccountId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
